services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 2
    depends_on:
      - kafka
      - mysql
      - mongo
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka-container
    platform: linux/amd64
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092" ]
      interval: 10s
      timeout: 5s
      retries: 2
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper-container
    platform: linux/amd64
    ports:
      - "2181:2181"
    environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: ["CMD", "echo", "ruok", "|", "nc", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 2
    networks:
      - app-network

  debezium:
    image: quay.io/debezium/connect:1.9
    container_name: debezium-container
    platform: linux/amd64
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
    depends_on:
      - kafka
    networks:
      - app-network

  mysql:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: mysql_database
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - ./data/DATA.sql:/docker-entrypoint-initdb.d/DATA.sql

  mongo:
    image: mongo
    container_name: mongo-container
    ports:
      - "27017:27017"
    networks:
      - app-network
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: test
        MONGO_INITDB_DATABASE: mongo_database
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all", "--keyFile", "/etc/mongo-keyfile" ]
    volumes:
    - ./mongo-keyfile:/etc/mongo-keyfile
    - ./data/DATA.js:/docker-entrypoint-initdb.d/DATA.js

networks:
  app-network:
    driver: bridge
